Added social accounts verification logic
Kajol-Kumari/InfluMart pull request #83
Opened 2024-06-24 11:58 UTC by Asymtode712

## Description

Added the total logic for social accounts verification by creating `socialsverification.js` 

@RohitGupta1237 You have to generate the API tokens for each Social on your part, I would provide the steps for doing it, so that it would be easy for you

2024-06-24 14:39 UTC, Kajol-Kumari requested changes
Never Ever add `node_modules` in your prs!

2024-06-24 17:04 UTC, Asymtode712 commented
@Kajol-Kumari So sorry, actually the `.gitignore` file wasn't properly configured

2024-06-25 04:14 UTC, Kajol-Kumari commented
@Asymtode712 i am still seeing `node_module` folder in this pr, either clean that up or please raise a new pr which i can review

2024-06-25 04:57 UTC, Asymtode712 commented
@Kajol-Kumari Done....Sorry once again😓🙏🏼

2024-06-25 07:42 UTC, Kajol-Kumari requested changes
The package-lock.json file should also not be there as all the backend required dependencies should be under `backend/package.json` file

2024-06-25 07:42 UTC, Kajol-Kumari commented on backend/.gitignore
> -node_modules/
please retain this as well as it seems to be working for few folks.

2024-06-25 07:42 UTC, Kajol-Kumari commented on backend/controllers/socialsverification.js
> +  const instagramApiUrl = 'https://graph.instagram.com/me';
please keep this either in .env config or in a constant file

2024-06-25 07:42 UTC, Kajol-Kumari commented on backend/controllers/socialsverification.js
> +  const youtubeApiUrl = 'https://www.googleapis.com/youtube/v3/channels';
please keep this either in .env config or in a constant file

2024-06-25 07:42 UTC, Kajol-Kumari commented on backend/controllers/socialsverification.js
> +  const facebookApiUrl = 'https://graph.facebook.com/v15.0/me';
please keep this either in .env config or in a constant file

2024-06-25 07:42 UTC, Kajol-Kumari commented on backend/controllers/socialsverification.js
> +    'https://api.twitter.com/oauth/request_token',
please keep these 2 endpoints either in .env config or in a constant file

2024-06-25 07:42 UTC, Kajol-Kumari commented on package.json
> +{
what's the purpose of this new `package.json` file? why can't we have the dependencies in `backend/package.json` file?

2024-06-25 09:45 UTC, RohitGupta1237 commented
@Asymtode712 The logic is not working in the way we wanted it to  work.

2024-06-26 07:41 UTC, closed without merging