[FrontEnd] preview page show hide and refactor preview Fixed
Kajol-Kumari/InfluMart pull request #87
Opened 2024-06-24 18:17 UTC by Hemu21

## Description:

All mentioned changes are made. I had most of the refactoring done as much as possible. 

## Issue

[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/86) resolve #86

2024-06-24 18:18 UTC, Hemu21 commented
@Kajol-Kumari  can you please check.

2024-06-25 04:13 UTC, Kajol-Kumari requested changes
<img width="1511" alt="Screenshot 2024-06-25 at 9 40 54 AM" src="https://github.com/Kajol-Kumari/InfluMart/assets/44888949/4145c004-f8dc-4b40-9d32-93cc478aefdb">

- [ ] The signup button should be removed no? as we are already showing `Create a new Account? Sign Up`
- [ ] The password eye icon isn't shown during signIn/signUp, can we add there as well?

2024-06-25 05:31 UTC, Hemu21 commented
@Kajol-Kumari  updated all requested changes are done. can you please check

2024-06-25 06:18 UTC, Kajol-Kumari approved these changes

2024-06-25 06:19 UTC, merged